nonprod:
	ng build --deploy-url static/angular/dist/
	cp dist/index.html ../../templates/index_angular.html
prod:
	ng build --prod --deploy-url static/angular/dist/
	cp dist/index.html ../../templates/index_angular.html
