// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Problem.proto

package com.auacm.api.proto;

public final class Problem {
  private Problem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProblemWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.auacm.api.proto.ProblemWrapper)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.auacm.api.proto.ProblemWrapper}
   */
  public  static final class ProblemWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.auacm.api.proto.ProblemWrapper)
      ProblemWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProblemWrapper.newBuilder() to construct.
    private ProblemWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProblemWrapper() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProblemWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auacm.api.proto.Problem.ProblemWrapper.class, com.auacm.api.proto.Problem.ProblemWrapper.Builder.class);
    }

    public interface ProblemResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.auacm.api.proto.ProblemWrapper.ProblemResponse)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 pid = 1;</code>
       */
      long getPid();

      /**
       * <code>string shortname = 2;</code>
       */
      java.lang.String getShortname();
      /**
       * <code>string shortname = 2;</code>
       */
      com.google.protobuf.ByteString
          getShortnameBytes();

      /**
       * <code>string name = 3;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 3;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string appeared = 4;</code>
       */
      java.lang.String getAppeared();
      /**
       * <code>string appeared = 4;</code>
       */
      com.google.protobuf.ByteString
          getAppearedBytes();

      /**
       * <code>string difficuty = 5;</code>
       */
      java.lang.String getDifficuty();
      /**
       * <code>string difficuty = 5;</code>
       */
      com.google.protobuf.ByteString
          getDifficutyBytes();

      /**
       * <code>int64 added = 6;</code>
       */
      long getAdded();

      /**
       * <code>int32 competitionId = 7;</code>
       */
      int getCompetitionId();

      /**
       * <code>string url = 8;</code>
       */
      java.lang.String getUrl();
      /**
       * <code>string url = 8;</code>
       */
      com.google.protobuf.ByteString
          getUrlBytes();
    }
    /**
     * Protobuf type {@code com.auacm.api.proto.ProblemWrapper.ProblemResponse}
     */
    public  static final class ProblemResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.auacm.api.proto.ProblemWrapper.ProblemResponse)
        ProblemResponseOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ProblemResponse.newBuilder() to construct.
      private ProblemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ProblemResponse() {
        pid_ = 0L;
        shortname_ = "";
        name_ = "";
        appeared_ = "";
        difficuty_ = "";
        added_ = 0L;
        competitionId_ = 0;
        url_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ProblemResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                pid_ = input.readInt64();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                shortname_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                appeared_ = s;
                break;
              }
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();

                difficuty_ = s;
                break;
              }
              case 48: {

                added_ = input.readInt64();
                break;
              }
              case 56: {

                competitionId_ = input.readInt32();
                break;
              }
              case 66: {
                java.lang.String s = input.readStringRequireUtf8();

                url_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse.class, com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse.Builder.class);
      }

      public static final int PID_FIELD_NUMBER = 1;
      private long pid_;
      /**
       * <code>int64 pid = 1;</code>
       */
      public long getPid() {
        return pid_;
      }

      public static final int SHORTNAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object shortname_;
      /**
       * <code>string shortname = 2;</code>
       */
      public java.lang.String getShortname() {
        java.lang.Object ref = shortname_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shortname_ = s;
          return s;
        }
      }
      /**
       * <code>string shortname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getShortnameBytes() {
        java.lang.Object ref = shortname_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shortname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 3;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int APPEARED_FIELD_NUMBER = 4;
      private volatile java.lang.Object appeared_;
      /**
       * <code>string appeared = 4;</code>
       */
      public java.lang.String getAppeared() {
        java.lang.Object ref = appeared_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appeared_ = s;
          return s;
        }
      }
      /**
       * <code>string appeared = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAppearedBytes() {
        java.lang.Object ref = appeared_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appeared_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DIFFICUTY_FIELD_NUMBER = 5;
      private volatile java.lang.Object difficuty_;
      /**
       * <code>string difficuty = 5;</code>
       */
      public java.lang.String getDifficuty() {
        java.lang.Object ref = difficuty_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          difficuty_ = s;
          return s;
        }
      }
      /**
       * <code>string difficuty = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDifficutyBytes() {
        java.lang.Object ref = difficuty_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          difficuty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ADDED_FIELD_NUMBER = 6;
      private long added_;
      /**
       * <code>int64 added = 6;</code>
       */
      public long getAdded() {
        return added_;
      }

      public static final int COMPETITIONID_FIELD_NUMBER = 7;
      private int competitionId_;
      /**
       * <code>int32 competitionId = 7;</code>
       */
      public int getCompetitionId() {
        return competitionId_;
      }

      public static final int URL_FIELD_NUMBER = 8;
      private volatile java.lang.Object url_;
      /**
       * <code>string url = 8;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        }
      }
      /**
       * <code>string url = 8;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (pid_ != 0L) {
          output.writeInt64(1, pid_);
        }
        if (!getShortnameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, shortname_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
        }
        if (!getAppearedBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appeared_);
        }
        if (!getDifficutyBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, difficuty_);
        }
        if (added_ != 0L) {
          output.writeInt64(6, added_);
        }
        if (competitionId_ != 0) {
          output.writeInt32(7, competitionId_);
        }
        if (!getUrlBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 8, url_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (pid_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, pid_);
        }
        if (!getShortnameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, shortname_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
        }
        if (!getAppearedBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appeared_);
        }
        if (!getDifficutyBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, difficuty_);
        }
        if (added_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(6, added_);
        }
        if (competitionId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(7, competitionId_);
        }
        if (!getUrlBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, url_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse)) {
          return super.equals(obj);
        }
        com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse other = (com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse) obj;

        boolean result = true;
        result = result && (getPid()
            == other.getPid());
        result = result && getShortname()
            .equals(other.getShortname());
        result = result && getName()
            .equals(other.getName());
        result = result && getAppeared()
            .equals(other.getAppeared());
        result = result && getDifficuty()
            .equals(other.getDifficuty());
        result = result && (getAdded()
            == other.getAdded());
        result = result && (getCompetitionId()
            == other.getCompetitionId());
        result = result && getUrl()
            .equals(other.getUrl());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPid());
        hash = (37 * hash) + SHORTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getShortname().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + APPEARED_FIELD_NUMBER;
        hash = (53 * hash) + getAppeared().hashCode();
        hash = (37 * hash) + DIFFICUTY_FIELD_NUMBER;
        hash = (53 * hash) + getDifficuty().hashCode();
        hash = (37 * hash) + ADDED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAdded());
        hash = (37 * hash) + COMPETITIONID_FIELD_NUMBER;
        hash = (53 * hash) + getCompetitionId();
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.auacm.api.proto.ProblemWrapper.ProblemResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.auacm.api.proto.ProblemWrapper.ProblemResponse)
          com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse.class, com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse.Builder.class);
        }

        // Construct using com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          pid_ = 0L;

          shortname_ = "";

          name_ = "";

          appeared_ = "";

          difficuty_ = "";

          added_ = 0L;

          competitionId_ = 0;

          url_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_descriptor;
        }

        public com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse getDefaultInstanceForType() {
          return com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse.getDefaultInstance();
        }

        public com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse build() {
          com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse buildPartial() {
          com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse result = new com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse(this);
          result.pid_ = pid_;
          result.shortname_ = shortname_;
          result.name_ = name_;
          result.appeared_ = appeared_;
          result.difficuty_ = difficuty_;
          result.added_ = added_;
          result.competitionId_ = competitionId_;
          result.url_ = url_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse) {
            return mergeFrom((com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse other) {
          if (other == com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse.getDefaultInstance()) return this;
          if (other.getPid() != 0L) {
            setPid(other.getPid());
          }
          if (!other.getShortname().isEmpty()) {
            shortname_ = other.shortname_;
            onChanged();
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (!other.getAppeared().isEmpty()) {
            appeared_ = other.appeared_;
            onChanged();
          }
          if (!other.getDifficuty().isEmpty()) {
            difficuty_ = other.difficuty_;
            onChanged();
          }
          if (other.getAdded() != 0L) {
            setAdded(other.getAdded());
          }
          if (other.getCompetitionId() != 0) {
            setCompetitionId(other.getCompetitionId());
          }
          if (!other.getUrl().isEmpty()) {
            url_ = other.url_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long pid_ ;
        /**
         * <code>int64 pid = 1;</code>
         */
        public long getPid() {
          return pid_;
        }
        /**
         * <code>int64 pid = 1;</code>
         */
        public Builder setPid(long value) {
          
          pid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 pid = 1;</code>
         */
        public Builder clearPid() {
          
          pid_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object shortname_ = "";
        /**
         * <code>string shortname = 2;</code>
         */
        public java.lang.String getShortname() {
          java.lang.Object ref = shortname_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            shortname_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string shortname = 2;</code>
         */
        public com.google.protobuf.ByteString
            getShortnameBytes() {
          java.lang.Object ref = shortname_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            shortname_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string shortname = 2;</code>
         */
        public Builder setShortname(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          shortname_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string shortname = 2;</code>
         */
        public Builder clearShortname() {
          
          shortname_ = getDefaultInstance().getShortname();
          onChanged();
          return this;
        }
        /**
         * <code>string shortname = 2;</code>
         */
        public Builder setShortnameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          shortname_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 3;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 3;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 3;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 3;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 3;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object appeared_ = "";
        /**
         * <code>string appeared = 4;</code>
         */
        public java.lang.String getAppeared() {
          java.lang.Object ref = appeared_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            appeared_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string appeared = 4;</code>
         */
        public com.google.protobuf.ByteString
            getAppearedBytes() {
          java.lang.Object ref = appeared_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            appeared_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string appeared = 4;</code>
         */
        public Builder setAppeared(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          appeared_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string appeared = 4;</code>
         */
        public Builder clearAppeared() {
          
          appeared_ = getDefaultInstance().getAppeared();
          onChanged();
          return this;
        }
        /**
         * <code>string appeared = 4;</code>
         */
        public Builder setAppearedBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          appeared_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object difficuty_ = "";
        /**
         * <code>string difficuty = 5;</code>
         */
        public java.lang.String getDifficuty() {
          java.lang.Object ref = difficuty_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            difficuty_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string difficuty = 5;</code>
         */
        public com.google.protobuf.ByteString
            getDifficutyBytes() {
          java.lang.Object ref = difficuty_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            difficuty_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string difficuty = 5;</code>
         */
        public Builder setDifficuty(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          difficuty_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string difficuty = 5;</code>
         */
        public Builder clearDifficuty() {
          
          difficuty_ = getDefaultInstance().getDifficuty();
          onChanged();
          return this;
        }
        /**
         * <code>string difficuty = 5;</code>
         */
        public Builder setDifficutyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          difficuty_ = value;
          onChanged();
          return this;
        }

        private long added_ ;
        /**
         * <code>int64 added = 6;</code>
         */
        public long getAdded() {
          return added_;
        }
        /**
         * <code>int64 added = 6;</code>
         */
        public Builder setAdded(long value) {
          
          added_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 added = 6;</code>
         */
        public Builder clearAdded() {
          
          added_ = 0L;
          onChanged();
          return this;
        }

        private int competitionId_ ;
        /**
         * <code>int32 competitionId = 7;</code>
         */
        public int getCompetitionId() {
          return competitionId_;
        }
        /**
         * <code>int32 competitionId = 7;</code>
         */
        public Builder setCompetitionId(int value) {
          
          competitionId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 competitionId = 7;</code>
         */
        public Builder clearCompetitionId() {
          
          competitionId_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object url_ = "";
        /**
         * <code>string url = 8;</code>
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            url_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string url = 8;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string url = 8;</code>
         */
        public Builder setUrl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string url = 8;</code>
         */
        public Builder clearUrl() {
          
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        /**
         * <code>string url = 8;</code>
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          url_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.auacm.api.proto.ProblemWrapper.ProblemResponse)
      }

      // @@protoc_insertion_point(class_scope:com.auacm.api.proto.ProblemWrapper.ProblemResponse)
      private static final com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse();
      }

      public static com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ProblemResponse>
          PARSER = new com.google.protobuf.AbstractParser<ProblemResponse>() {
        public ProblemResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new ProblemResponse(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ProblemResponse> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ProblemResponse> getParserForType() {
        return PARSER;
      }

      public com.auacm.api.proto.Problem.ProblemWrapper.ProblemResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.auacm.api.proto.Problem.ProblemWrapper)) {
        return super.equals(obj);
      }
      com.auacm.api.proto.Problem.ProblemWrapper other = (com.auacm.api.proto.Problem.ProblemWrapper) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auacm.api.proto.Problem.ProblemWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.auacm.api.proto.Problem.ProblemWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.auacm.api.proto.ProblemWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.auacm.api.proto.ProblemWrapper)
        com.auacm.api.proto.Problem.ProblemWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.auacm.api.proto.Problem.ProblemWrapper.class, com.auacm.api.proto.Problem.ProblemWrapper.Builder.class);
      }

      // Construct using com.auacm.api.proto.Problem.ProblemWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.auacm.api.proto.Problem.internal_static_com_auacm_api_proto_ProblemWrapper_descriptor;
      }

      public com.auacm.api.proto.Problem.ProblemWrapper getDefaultInstanceForType() {
        return com.auacm.api.proto.Problem.ProblemWrapper.getDefaultInstance();
      }

      public com.auacm.api.proto.Problem.ProblemWrapper build() {
        com.auacm.api.proto.Problem.ProblemWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.auacm.api.proto.Problem.ProblemWrapper buildPartial() {
        com.auacm.api.proto.Problem.ProblemWrapper result = new com.auacm.api.proto.Problem.ProblemWrapper(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.auacm.api.proto.Problem.ProblemWrapper) {
          return mergeFrom((com.auacm.api.proto.Problem.ProblemWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.auacm.api.proto.Problem.ProblemWrapper other) {
        if (other == com.auacm.api.proto.Problem.ProblemWrapper.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.auacm.api.proto.Problem.ProblemWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.auacm.api.proto.Problem.ProblemWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.auacm.api.proto.ProblemWrapper)
    }

    // @@protoc_insertion_point(class_scope:com.auacm.api.proto.ProblemWrapper)
    private static final com.auacm.api.proto.Problem.ProblemWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.auacm.api.proto.Problem.ProblemWrapper();
    }

    public static com.auacm.api.proto.Problem.ProblemWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProblemWrapper>
        PARSER = new com.google.protobuf.AbstractParser<ProblemWrapper>() {
      public ProblemWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProblemWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProblemWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProblemWrapper> getParserForType() {
      return PARSER;
    }

    public com.auacm.api.proto.Problem.ProblemWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_auacm_api_proto_ProblemWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_auacm_api_proto_ProblemWrapper_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&src/main/resources/proto/Problem.proto" +
      "\022\023com.auacm.api.proto\"\252\001\n\016ProblemWrapper" +
      "\032\227\001\n\017ProblemResponse\022\013\n\003pid\030\001 \001(\003\022\021\n\tsho" +
      "rtname\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\020\n\010appeared\030\004" +
      " \001(\t\022\021\n\tdifficuty\030\005 \001(\t\022\r\n\005added\030\006 \001(\003\022\025" +
      "\n\rcompetitionId\030\007 \001(\005\022\013\n\003url\030\010 \001(\tb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_auacm_api_proto_ProblemWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_auacm_api_proto_ProblemWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_auacm_api_proto_ProblemWrapper_descriptor,
        new java.lang.String[] { });
    internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_descriptor =
      internal_static_com_auacm_api_proto_ProblemWrapper_descriptor.getNestedTypes().get(0);
    internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_auacm_api_proto_ProblemWrapper_ProblemResponse_descriptor,
        new java.lang.String[] { "Pid", "Shortname", "Name", "Appeared", "Difficuty", "Added", "CompetitionId", "Url", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
